config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: :show
  resource  :feed,  only: :show

  namespace :admin do
    root 'posts#index'

    resources :posts, only: %i[new create edit update destroy]
  end

  get 'posts.atom', to: redirect('feed.atom')

  get 'up',             to: 'rails/health#show',        as: :rails_health_check
  get 'service-worker', to: 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest',       to: 'rails/pwa#manifest',       as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/marksmith/renderer.rb
class Marksmith::Renderer
  def initialize(body:)
    @body = body
  end

  def render
    Commonmarker.to_html(@body, options: {
      render: {unsafe: true}
    })
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :attachments

  validates :title, presence: true
  validates :body,  presence: true

  before_save :set_attachments
  after_commit :purge_unattached_blobs

  private

  def set_attachments
    signed_ids = []

    Commonmarker.parse(body).walk do |node|
      case node.type
      when :link, :image
        if %r{\A/rails/active_storage/blobs/(?:redirect/|proxy/)?(?<signed_id>\S+)/} =~ node.url
          signed_ids << signed_id
        end
      end
    end

    self.attachments = signed_ids
  end

  def purge_unattached_blobs
    ActiveStorage::Blob.unattached.each(&:purge)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'

  admin_auth = Rails.application.config_for(:admin_auth)

  if admin_auth.enabled
    http_basic_authenticate_with **admin_auth.slice(:name, :password)
  end

  def index
    @posts = Post.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      publish

      redirect_to admin_root_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      publish

      redirect_to admin_root_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Post.find(params.expect(:id)).destroy!

    redirect_to admin_root_path, status: :see_other
  end

  private

  def post_params
    params.expect(post: %i[title body])
  end

  def publish
    return unless Rails.application.config_for(:app).websub

    Fetch::API.fetch 'https://pubsubhubbub.appspot.com/publish', **{
      method: 'POST',

      body: Fetch::URLSearchParams.new(
        "hub.mode": 'publish',
        "hub.url":  feed_url(format: :atom)
      )
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  rescue_from ActiveRecord::StatementInvalid do |e|
    if e.message =~ /cannot rollback - no transaction is active/
      head :method_not_allowed
    else
      raise e
    end
  end
end

app/controllers/debug_controller.rb
class DebugController < ApplicationController
  skip_forgery_protection

  def write
    sleep 1

    current = ActiveRecord::Base.connection.select_value("PRAGMA user_version")
    ActiveRecord::Base.connection.execute "PRAGMA user_version = #{current + 1}"

    head :ok
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def show
    @posts = Post.order(id: :desc).limit(20)

    fresh_when @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(id: :desc).page(params[:page]).per(20)
  end

  def show
    @post = Post.find(params.expect(:id))
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/admin/posts/_form.html.erb
<%# locals: (post:) %>

<% unless post.errors.empty? %>
  <ul>
    <% post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: post, url: [:admin, post] do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :body, 'Body', class: 'form-label' %>
    <%= form.marksmith :body, required: true %>
  </div>

  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/admin/posts/edit.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active"><%= @post.title %></li>
<% end %>

<%= render 'form', post: @post %>

<hr />

<%= button_to 'Delete', admin_post_path(@post), method: :delete, class: 'btn btn-danger' %>

app/views/admin/posts/index.html.erb
<div>
  <%= link_to 'New Post', new_admin_post_path, class: 'btn btn-outline-primary' %>
</div>

<div class="list-group">
  <% @posts.each do |post| %>
    <%= link_to edit_admin_post_path(post), class: 'list-group-item list-group-item-action d-flex gap-3' do %>
      <time>
        <%= l post.created_at.to_date %>
      </time>

      <div class="text-truncate">
        <%= post.title %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admin/posts/new.html.erb
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">New Post</li>
<% end %>

<%= render 'form', post: @post %>

app/views/feeds/show.atom.erb
<?xml version="1.0" encoding="utf-8"?>

<feed xmlns="http://www.w3.org/2005/Atom">
  <title>pong.ursm.jp</title>
  <link href="<%= root_url %>" />
  <link rel="self" href="<%= feed_url(format: :atom) %>" />
  <link rel="hub" href="https://pubsubhubbub.appspot.com" />
  <id><%= root_url %></id>
  <updated><%= @posts.first.created_at.iso8601 %></updated>

  <% @posts.each do |post| %>
    <entry>
      <title><%= post.title %></title>
      <link href="<%= post_url(post) %>" />
      <id><%= post_url(post) %></id>
      <updated><%= post.updated_at.iso8601 %></updated>
      <content type="html"><%= marksmithed(post.body) %></content>

      <author>
        <name>ursm</name>
      </author>
    </entry>
  <% end %>
</feed>

app/views/layouts/admin.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= content_for(:title) || 'pong.ursm.jp' %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag 'admin', "data-turbo-track": 'reload' %>
    <%= stylesheet_link_tag 'marksmith', "data-turbo-track": 'reload' %>
    <%= javascript_importmap_tags 'admin' %>
  </head>

  <body>
    <div class="container vstack gap-3">
      <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item">
            <%= link_to 'pong.ursm.jp', :root %>
          </li>

          <%= tag.li class: ['breadcrumb-item', active: current_page?(:admin_root)] do %>
            <%= link_to_unless_current 'admin', :admin_root %>
          <% end %>

          <%= yield :breadcrumb %>
        </ol>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head prefix="og: https://ogp.me/ns#">
    <title><%= [@page_title, 'pong.ursm.jp'].compact.join(' - ') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="alternate" type="application/atom+xml" href="<%= feed_url(format: :atom) %>">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <h1 class="m-0"><%= link_to 'pong.ursm.jp', :root %></h1>

      <main class="stack">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<article>
  <h1><%= link_to post.title, post %></h1>
  <%== marksmithed post.body %>
  <time><%= l post.created_at&.to_date || Date.current %></time>
</article>

app/views/posts/index.atom.erb
<?xml version="1.0" encoding="utf-8"?>

<feed xmlns="http://www.w3.org/2005/Atom">
  <title>pong.ursm.jp</title>
  <link href="<%= root_url %>" />
  <link rel="self" href="<%= posts_url(format: :atom) %>" />
  <link rel="hub" href="https://pubsubhubbub.appspot.com" />
  <id><%= root_url %></id>
  <updated><%= @posts.first.created_at.iso8601 %></updated>

  <% @posts.each do |post| %>
    <entry>
      <title><%= post.title %></title>
      <link href="<%= post_url(post) %>" />
      <id><%= post_url(post) %></id>
      <updated><%= post.updated_at.iso8601 %></updated>

      <content type="html">
        <![CDATA[<%== marksmithed(post.body) %>]]>
      </content>

      <author>
        <name>ursm</name>
      </author>
    </entry>
  <% end %>
</feed>

app/views/posts/index.html.erb
<%= render partial: 'post', collection: @posts %>

app/views/posts/show.html.erb
<% @page_title = @post.title %>

<% content_for :head do %>
  <meta name="description" content="<%= strip_tags(marksmithed(@post.body)).strip.truncate(120) %>">
  <meta property="og:url" content="<%= post_url(@post) %>">
  <meta property="og:title" content="<%= @post.title %>">
  <meta name="twitter:card" content="summary">
<% end %>

<%= render @post %>